---
title: "Strings and Factors"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(forcats)

library(p8105.datasets)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

# Let's do strings
```{r}
string_vec = c("my", "name", "is", "lizy")

str_detect(string_vec, "a")

str_replace(string_vec, "lizy", "Lizy")

str_replace(string_vec, "i", "I")

```

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "^i think")
#carrot indicates to find the string in the beginning of the line
#dollar sign indicatest of ind the string at the end of the line
str_detect(string_vec, "i think$")
```

```{r}
string_vec = c(
  "Time for a Pumpkin Spice Latte!",
  "went to the #pumpkinpatch last weekend",
  "Pumpkin Pie is obviously the best pie",
  "SMASHING PUMPKINS -- LIVE IN CONCERT!!"
  )

str_detect(string_vec,"[Pp]umpkin")
#multiple options for "P or p" inside the bracket will detect both upper and lowercase

```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "^[0-9][a-zA-Z]")
#any numbers [0-9]
#any lowercase letter[a-z]
#any uppercase letter[A-Z]
```

```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.11")
#the "." matches with any character
```

How things start to get real strange...
```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

#looking for open bracket
str_detect(string_vec, "\\[")
#two slashes before indicates to what we're looking for 
```

## Factors ...
```{r}
sex_vec = factor(c("male", "male", "female", "female"))

as.numeric(sex_vec)
```

do some releveling...

```{r}
sex_vec = fct_relevel(sex_vec, "male")
# changed underlying structure: male first, female second
as.numeric(sex_vec)
```


## Revisig a lot of examples!

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = read_html(nsduh_url)

# pieces I actually need 
marj_use_df = table_marj = table_marj = 
  read_html(nsduh_url) %>%  
  html_table() %>% 
  first() %>% 
  slice(-1) %>% 
  select(-contains("P Value")) %>% 
  pivot_longer(
    cols = -State,
    names_to = "age_year",
    values_to = "percent", 
  ) %>% 
  separate(age_year, into = c("age", "year"), sep = "\\(") %>% 
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_remove(percent, "[a-c]$"),
    percent = as.numeric(percent)
  )

# slice -> select and remove the particular row
```

```{r}

```


```{r}
marj_use_df %>% 
  filter(age == "12-17", 
         !(State %in% c("Total U.S.", "South"))) %>%  
  mutate(
    State = fct_reorder(State, percent)
  ) %>% 
  ggplot(aes(x = State, y = percent, color = year)) + 
  geom_point() + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1))

# the !(State) filter takes out the Total US or South (regional data instead of state-wide data)
```

## NYC Restaurant Inspections

```{r}
data("rest_inspec")

rest_inspec %>% 
  count(boro, grade) %>% 
  pivot_wider(
    names_from = grade,
    values_from = n
  )
```

```{r}
rest_inspec =
  rest_inspec %>% 
  filter(
    str_detect(grade, "[A-C]"),
    !(boro == "Missing")
  )
  
```
```{r}
rest_inspec %>% 
  mutate(dba = str_to_sentence(dba)) %>% 
  filter(str_detect (dba, "Pizza")) 
```

```{r}
rest_inspec %>% 
  mutate(dba = str_to_sentence(dba)) %>% 
  filter(str_detect (dba, "Pizza")) %>% 
  mutate(boro = fct_infreq(boro)) %>% 
  ggplot(aes(x = boro)) +
  geom_bar()
```

```{r}
rest_inspec %>% 
  mutate(dba = str_to_sentence(dba)) %>% 
  filter(str_detect (dba, "Pizza")) %>% 
  mutate(boro = fct_relevel(boro, "STATEN ISLAND")) %>% 
  ggplot(aes(x = boro)) +
  geom_bar()
```

```{r}
rest_inspec %>% 
  mutate(dba = str_to_sentence(dba)) %>% 
  filter(str_detect (dba, "Pizza")) %>% 
  mutate(
    boro = fct_infreq(boro),
    boro = str_replace(boro, "MANHATTAN", "THE CITY")) %>% 
  ggplot(aes(x = boro)) +
  geom_bar()

#put it in order, updated manhattan to the city, and forced it back into alphabetical order making "THE CITY" to be the last in order 
```

```{r}
rest_inspec %>% 
  mutate(dba = str_to_sentence(dba)) %>% 
  filter(str_detect (dba, "Pizza")) %>% 
  mutate(
    boro = fct_infreq(boro),
    boro = fct_recode(boro, "THE CITY" = "MANHATTAN")) %>% 
  ggplot(aes(x = boro)) +
  geom_bar()

##using fct_recode will just replace the name without changing the order of the graph
``` 
One last thing on factors ...

```{r}
rest_inspec %>% 
  mutate(dba = str_to_sentence(dba)) %>% 
  filter(str_detect(dba, "Pizza")) %>% 
  mutate(boro = fct_infreq(boro)) %>% 
  lm(zipcode ~ boro, data = .)

```